---
--- Generated by Luanalysis
--- Created by Lenovo.
--- DateTime: 2023/1/16 20:52
---

local lockKey = 'lock'
local limitQPS = KEYS[1]
local timeOut = KEYS[2]

local res = tonumber(redis.call("get", lockKey))
if not res then
    --设置过期时间
    redis.call("set", lockKey, 1)
    redis.call("expire", lockKey, timeOut)
else
    if res < limitQPS then
        redis.call("incr", lockKey)
    else
        return 0
    end
end

