spring:
  rabbitmq:
    #服务器地址
    host: 127.0.0.1
    #用户名
    username: admin
    #密码
    password: 123456
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 5
        #消费者最大数量
        max-concurrency: 15
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 10
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: false
        #开启手动确认
        acknowledge-mode: manual
    template:
      #SpringBoot本身的重试机制和MQ没有关系：应用于发送方从一开始就连不上 MQ
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间 默认1000ms
        initial-interval: 1000
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0
        #发布确认 交换机-队列
    publisher-returns: true
    #发布确认 生产者-broker
    publisher-confirm-type: correlated

  thymeleaf:
    #    关闭缓存
    cache: false
    prefix: classpath:/templates/

  #  这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.0使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      #      连接池名
      pool-name: DateHikariCP
      #      最小空闲连接数
      minimum-idle: 5
      #      空闲连接最大存活时间默认600000(10min)
      idle-timeout: 1800000
      #      最大连接数 默认10
      maximum-pool-size: 10
      #      从连接池返回的连接自动提交
      auto-commit: true
      #      连接最大存活时间,0表示永久存活,默认180000(30min)
      max-lifetime: 1800000
      #      连接超时时间 默认30s
      connection-timeout: 30000
      #      测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #邮箱验证码配置
  mail:
    #smtp服务主机
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: richerlv@foxmail.com
    #授权码
    password: lazeewrckazpieac
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    #静态资源处理
    resources:
      #启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600
      chain:
        #资源链中启用缓存，默认启用
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #        启用压缩资源（gzip，brotil)
        compressed: true
        #启用h5应用缓存
        html-application-cache: true
        #      静态资源位置
      static-locations: classpath:/static/
  data:
    redis:
      port: 6379
      database: 0
      #    连接超时时间
      connect-timeout: 10000ms
      lettuce:
        pool:
          #        最大连接数
          max-active: 1024
          #        最大连接阻塞等待时间
          max-wait: 10000ms
          #        最大空闲连接
          max-idle: 200
          #        最小空闲连接
          min-idle: 5


mybatis:
  #  配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.example.seckill.pojo

# Mybatis SQL打印(方法接口所在的包,不是Mapper.xml所在的包)
logging:
  level:
    com.example.bookreaders_backend.mapper: debug




