spring:

  thymeleaf:
    #    关闭缓存
    cache: false

  #  这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.0使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      #      连接池名
      pool-name: DateHikariCP
      #      最小空闲连接数
      minimum-idle: 5
      #      空闲连接最大存活时间默认600000(10min)
      idle-timeout: 1800000
      #      最大连接数 默认10
      maximum-pool-size: 10
      #      从连接池返回的连接自动提交
      auto-commit: true
      #      连接最大存活时间,0表示永久存活,默认180000(30min)
      max-lifetime: 1800000
      #      连接超时时间 默认30s
      connection-timeout: 30000
      #      测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  web:
    #静态资源处理
    resources:
      #启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600
      chain:
        #资源链中启用缓存，默认启用
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #        启用压缩资源（gzip，brotil)
        compressed: true
        #启用h5应用缓存
        html-application-cache: true
        #      静态资源位置
      static-locations: classpath:/static/
  data:
    redis:
      port: 6379
      database: 0
      #    连接超时时间
      connect-timeout: 10000ms
      lettuce:
        pool:
          #        最大连接数
          max-active: 1024
          #        最大连接阻塞等待时间
          max-wait: 10000ms
          #        最大空闲连接
          max-idle: 200
          #        最小空闲连接
          min-idle: 5


mybatis:
  #  配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.example.seckill.pojo

# Mybatis SQL打印(方法接口所在的包,不是Mapper.xml所在的包)
logging:
  level:
    com.example.bookreaders_backend.mapper: debug




